name: my cicd

on: 
  push:
    branches: ['main']

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Removed extra space
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn compile

  security-check:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trivy Installation
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Trivy Scan
        run: trivy fs --format json -o report-trivy.json .  # fixed 'sf' to 'fs' and proper flags

      - name: Install Gitleaks
        run: |
          sudo apt-get update
          sudo apt-get install -y gitleaks

      - name: Gitleaks Code Scan
        run: gitleaks detect --source . --report-path gitleaks-report.json -f json  # fixed flags

  test:
    runs-on: ubuntu-latest
    needs: security-check

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4  # fixed incorrect `checkout/setup-java`
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run Unit Tests
        run: mvn test
